### ISSUE TITLE
surprisingly small CPUE values for DFO-QCS

### ISSUE THREAD

**Issue by zoekitchel** [AquaAuma/FishGlob_data#30]
Noticed surprisingly low CPUE values for DFO-QCS

**Comment by zoekitchel** [comment]
Found issue in cleaning code where wgt/m^2 is divided by 1000000 m^2/km^2 instead of multiplied, fixed

**Comment by zoekitchel** [comment]
Same changes for Hectate Strait, Strait of Georgia, West Coast Haida Gwaii and West Coast Vancouver Island cleaning codes. Made all changes, but unfortunately can't get 
get_dfo-sog.R to run:
`> ######### Apply trimming per survey_unit method 2
> dat_new_method2 <- apply_trimming_per_survey_unit_method2(clean_sog)
`summarise()` has grouped output by 'survey_unit'. You can override using the `.groups` argument.
Error in if (ext@xmin > -360.01 & ext@xmax < 360.01 & ext@ymin > -90.01 & :
missing value where TRUE/FALSE needed`

**Comment by AquaAuma** [comment]
I have no error messages on my side when I run the flag functions, maybe it's an R package version thing?

**Comment by AquaAuma** [comment]
@zoekitchel, I found out why you encountered issues: 
- for DFO-SOG, the minimum criteria to apply trimming require for each survey unit to include at least two year of survey (works for DFO-SOG), and a minimum duration of 10 years (for DFO-SOG, min year is 2012, and max year is 2015, so the duration is 4 years), therefore we end up with an empty data frame and an error in the function. I've modified the function to add a print message and remove the warnings. The survey summary was also missing for DFO-SOG, since it's only 2 years, the graphs are not all interesting, but now it's there.
https://github.com/AquaAuma/FishGlob_data/blob/8337fb7088e6ead057ac6267efd158959186b602/functions/apply_trimming_method2.R#L47
https://github.com/AquaAuma/FishGlob_data/blob/8337fb7088e6ead057ac6267efd158959186b602/functions/apply_trimming_method2.R#L289
- for DFO-WCHG, there was a problem with the full_join() function so I fixed the code to add a join that does not create duplicates.
https://github.com/AquaAuma/FishGlob_data/blob/8337fb7088e6ead057ac6267efd158959186b602/functions/apply_trimming_method2.R#L203
- I've also found unwanted duplicates in the hauls.removed files, that I fixed in the function here https://github.com/AquaAuma/FishGlob_data/blob/8337fb7088e6ead057ac6267efd158959186b602/functions/apply_trimming_method2.R#L220 and I'll re-run all trimming functions for all surveys to fix the files
